apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: backend
  namespace: myapp
  labels:
    app.kubernetes.io/name: backend
    app.kubernetes.io/component: backend
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: backend
      app.kubernetes.io/component: backend
